import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { LinkButton } from "@/components/ui/button";
import { PreviewNotice } from "@/components/ui/notice";
import { PageHeading } from "@/components/ui/page-heading";
import { StatusBadge } from "@/components/ui/status-badge";
import { EResetaComposer } from "@/features/prescriptions/ereseta-composer";
import { getPatientForDoctor, getReferral, listPrescribableMedicines } from "@/lib/data/queries";

export const metadata: Metadata = { title: "Continuation e-reseta · TULAY" };

/**
 * Figma M6 — continuation e-reseta after escalation. Shown only for a patient
 * with an existing escalation. Reuses the e-reseta composer, so the UPSC is
 * generated by the backend, never typed by the doctor.
 */
export default async function ContinuationPage({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ patient?: string }>;
}) {
  const { id } = await params;
  const { patient: patientParam } = await searchParams;
  const referral = await getReferral(id);
  const patient = await getPatientForDoctor(referral?.patientId ?? patientParam ?? "");
  if (patient?.status !== "active") notFound();

  const referralLabel = referral ? referral.id : "New escalation";
  const bookHref = `/doctor/referrals/${referral?.id ?? "REF-PREVIEW"}/book?patient=${patient.id}`;

  return (
    <>
      <PageHeading
        title="Referral sent"
        description={`${patient.displayName} · ${referralLabel} · Hospital escalation created.`}
        actions={
          <>
            <StatusBadge tone="info">Escalation exists</StatusBadge>
            <LinkButton href="/doctor/referrals" variant="secondary">
              View referrals
            </LinkButton>
          </>
        }
      />
      <div className="mb-6">
        <PreviewNotice>The referral was not actually sent. Referrals are not connected yet.</PreviewNotice>
      </div>
      <h2 className="mb-1 text-xl font-medium">Keep maintenance care connected</h2>
      <p className="mb-5 text-sm text-secondary-500">
        Include a continuation e-reseta with this referral when maintenance medication is needed.
      </p>
      <EResetaComposer
        patient={{
          id: patient.id,
          displayName: patient.displayName,
          firstName: patient.firstName,
          philHealthId: patient.philHealthId,
        }}
        medicines={await listPrescribableMedicines()}
        referralId={referral?.id ?? "REF-PREVIEW"}
        bookHref={bookHref}
      />
      <div className="mt-6">
        <LinkButton href={bookHref} variant="secondary">
          Skip and book appointment
        </LinkButton>
      </div>
    </>
  );
}
